# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
pod 'IBMMobileFirstPlatformFoundation', '7.1.1'

pod 'Google/Analytics', '~> 1.0.0'
